config/routes.rb
Rails.application.routes.draw do
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
		resources :leads
		root "leads#index", as: :authenticated_root
	end
	match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
	match '', to: redirect("/#{I18n.default_locale}"), :via => [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
	translates :job_post

	validates :name, presence: true
	validates :email, presence: true
	validates :job_post, presence: true
	validates :company, presence: true

	def self.search(search)
		if search
			where(["name LIKE ? or email LIKE ? or job_post LIKE ? or company LIKE ?","%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			all			
		end		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery with: :exception
	before_action :set_locale

	around_action :user_time_zone, if: :current_user

private

	def set_locale
		I18n.locale = params[:locale] if params[:locale].present?
	end

	def default_url_options(options = {})
		{locale: I18n.locale}
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def user_time_zone(&block)
		Time.use_zone(current_user.time_zone, &block)
	end


end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :find_lead, only: [:show, :edit, :update, :destroy]

	def index
		@lead = Lead.search(params[:search])
	end

	def new
		@lead = Lead.new
	end

	def create

		@lead = Lead.new lead_params

		if @lead.save
			redirect_to @lead, notice: "Contact saved!"
		else
			render 'new', notice: "An error occured!"
		end
			
	end

	def show

	end

	def edit		

	end

	def update

		if @lead.update lead_params
			redirect_to @lead, notice: "Contact updated!"
		else
			render 'edit'
			
		end

	end

	def destroy
		@lead.destroy
		redirect_to leads_path
	end

	private

	def lead_params
		params.require(:lead).permit(:name, :email, :job_post, :company, :registered_on)
		
	end

	def find_lead
		@lead = Lead.find(params[:id])

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar">

      <ul class="nav-links">
          <li class="border-right"> <%= link_to I18n.t(".homeLinkName"), leads_path() %> </li>
          <li><%= link_to I18n.t(".newLeadName"), new_lead_path() %></li>
        </ul>         

        <ul class="language-links">
          <li><%= t ".languageName" %>: </li>
          <li><%= link_to_unless_current "English", locale: "en" %></li>
          <li><%= link_to_unless_current "Portugués", locale: "pt" %></li>
          <%= link_to_unless_current "Español", locale: "es" %>
        </ul> 
    </div>

    <br/><Br/>

    <%= yield %>







  </body>
</html>

app/views/leads/_form.html.erb
<%= form_for @lead do |f| %>
	<% if @lead.errors.any? %>
		<h2><%= pluralize(@lead.errors.count, "error") %> raised. Please correct them to proceed.</h2>
		<ul>
			<% @lead.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>

			<% end %>
		</ul>
	<% end %>

	<%= f.label :name, Lead.human_attribute_name(:name) %><br/>
	<%= f.text_field :name, :required => "required" %><br/><br/>

	<%= f.label :email, Lead.human_attribute_name(:email) %><br/>
	<%= f.email_field :email, :required => "required" %><br/><br/>

	<%= f.label :job_post, Lead.human_attribute_name(:job_post) %><br/>
	<%= f.text_field :job_post, :required => "required" %><br/><br/>

	<%= f.label :company, Lead.human_attribute_name(:company) %><br/>
	<%= f.text_field :company, :required => "required" %><br/><br/>

	<%= f.submit I18n.t(".formName"), class: "add-lead-button" %>

<% end %>

app/views/leads/edit.html.erb
<h2 class="welcomeMessage"><%= t ".editLead" %></h2>

<%= render 'form' %>

app/views/leads/index.html.erb
<h2 class="welcomeMessage"><%= t ".welcomeWord" %></h2>

<%= form_tag leads_path, :method => 'get' do %>

	<p class="search">
		<%= text_field_tag :search, params[:search], placeholder: 'Search a lead', :required => "required" %>

		<%= submit_tag "search", :class => "submit-search", :name => nil %>
	</p>

<% end %>

<% @lead.each do |lead| %>

	<div class="box-profile">
		<b> <%= Lead.human_attribute_name(:name) %> : </b> <span class="float-right"><%= lead.name %></span><br/>
		<b> <%= Lead.human_attribute_name(:email) %> : </b> <span class="float-right"><%= lead.email %></span><br/>
		<b> <%= Lead.human_attribute_name(:job_post) %> : </b> <span class="float-right"><%= lead.job_post %></span><br/>
		<b> <%= Lead.human_attribute_name(:company) %> :</b><span class="float-right"> <%= lead.company %></span><br/>
		<b> <%= t ".createdTimeTitle" %> : </b> <%= I18n.l(lead.created_at.in_time_zone('Nairobi')) %><br/>

		<div class="manage-button"><%= link_to I18n.t(".viewDetailsName"), lead_path(lead) %></div>	
	</div>

<% end %> 

app/views/leads/new.html.erb
<h2 class="welcomeMessage"><%= t ".addLeadTitle" %></h2>

<%= render 'form' %>

app/views/leads/show.html.erb
<div class="lead-details">
	<%= Lead.human_attribute_name(:name) %>: <%= @lead.name %><br/>
	<hr>
	<%= Lead.human_attribute_name(:email) %>: <%= @lead.email %><br/>
	<hr>
	<%= Lead.human_attribute_name(:job_post) %>: <%= @lead.job_post %><br/>
	<hr>
	<%= Lead.human_attribute_name(:company) %>: <%= @lead.company %><br/>
	<hr>
	<br/>





<div class="edit-lead"><%= link_to I18n.t(".editName"), edit_lead_path(@lead) %></div>
<div class="delete-lead"><%= link_to I18n.t(".deleteName"), lead_path(@lead), method: :delete, data: { confirm: I18n.t(".confirmMessage") } %></div>

</div>